# File paths
keystore-path = './receiver/key_storage/'
password-file = './wallet_password.txt'

# Networking
eth-rpc-endpoint = "http://parity.goerli.ethnodes.brainbot.com:8545"
routing-mode = "pfs"
api-address = "localhost:5001"
matrix-server = "https://raidentransport.test001.env.raiden.network"
pathfinding-service-address = "https://pfs.raidentransport.test001.env.raiden.network"
network-id = "goerli"


# Misc
environment-type = "development"
accept-disclaimer = true

[log-config]
"raiden" = "ERROR"
