# File paths
keystore-path = './receiver/key_storage/'
password-file = './wallet_password.txt'

# Networking
matrix-server = "https://transport02.raiden.network"
eth-rpc-endpoint = "http://parity.kovan.ethnodes.brainbot.com:8545"
network-id = 42 

environment-type = "development"
accept-disclaimer = true

[log-config]
"raiden" = "ERROR"
